# Generated by Django 4.1.5 on 2023-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_dim_sale_ordertransaction_opentime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="server_conf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("host", models.CharField(max_length=200)),
                ("port", models.CharField(max_length=4)),
                ("database_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(model_name="room", name="host",),
        migrations.RemoveField(model_name="room", name="topic",),
        migrations.DeleteModel(name="Message",),
        migrations.DeleteModel(name="Room",),
        migrations.DeleteModel(name="Topic",),
    ]
